### PR TITLE
Make the switcher sticky at the top of the page

### PR DESCRIPTION
**Pull request by Cito**
I think usability would be improved if the switcher would always be visible. Here is one possible implementation.

### CODE REVIEW

**Comment by dohliam** [comment]
@Cito Wow, this looks great! :+1: Thank you for the suggestion and PR. :smile: 

I tested this out on a few different themes and one thing I noticed was that the white background can cause an issue with the dark themes (for example, [retro](https://dohliam.github.io/dropin-minimal-css/?retro) or [boot-cyborg](https://dohliam.github.io/dropin-minimal-css/?boot-cyborg)):

image

Removing the white background helps a bit, but makes the switcher div transparent which is probably not the desired effect:

image

Any thoughts on how this could be adjusted to suit both light and dark themes?

**Comment by Cito** [comment]
Thanks for the feedback, I was not sure whether this was appretiated. Will need to experiment a bit more when I find some time, maybe I can come up with something nicer.

**Comment by Cito** [comment]
I have pushed a new commit, the background color of the switcher will now be adapted to the loaded theme.

**Comment by dohliam** [comment]
@Cito This is incredible. I had no idea it was even possible to match backgrounds like this! Everything looks completely seamless. Thanks again for your contribution! :+1:

**Pull request merged**
