### PR TITLE
Escape all angle brackets

### PR DESCRIPTION
**Pull request by Cito**
Some angle brackets for the action buttons were not properly escaped.

### CODE REVIEW

**Comment by dohliam** [comment]
@Cito Good catch! I think this might be an upstream issue to raise with the [html5-test-page](https://github.com/cbracco/html5-test-page) project (which we are using to provide the sample HTML). I notice that this doesn't seem to cause a problem with rendering of the angle brackets as might be expected (at least in Firefox).

Have you found this causes any issues with rendering in other browsers or platforms?

**Comment by Cito** [comment]
@dohliam Yes, it probably doesn't matter, all browsers seem to accept that (at least in HTML5 - it would be different in XHTML). The reasons why the angle buttons need to be escaped for the buttons and not for the input is that they do not appear in an attribute there, but between the tags. So it's probably ok as it is and you should just close this PR. I noticed it only because I wondered why the buttons and the inputs looked differently in the a11yana style, and first suspected it might have something to do with that.

**Comment by dohliam** [comment]
Thanks for the explanation, that makes sense! You mentioned a11yana which got me intrigued, so I looked into it. This is what the inputs look like in a11yana on Firefox:

image

Is this the same as what you are seeing? If so I think I see what you mean, since the example inputs and the code below are differently styled, though that appears to be by design. If it's broken though I'd be glad to open this again as a bug.

**Comment by Cito** [comment]
@dohliam Yes, that's what I meant. I expected the "input type=button" to look the same as the "button type=button".

**Pull request closed without merging**
