### PR TITLE
Add Minimal stylesheet

### PR DESCRIPTION
**Pull request by TheLastZombie**
This adds [Minimal stylesheet](https://chr15m.github.io/minimal-stylesheet/) to the switcher. It also adds a missing closing bracket :)

Note that Minimal stylesheet doesn't have a license. If you don't want to include it because of that, feel free to close this.

### CODE REVIEW

**Comment by dohliam** [comment]
@TheLastZombie Thanks for the suggestion! It looks great.

There are only two minor issues with including this, one being the lack of a license as you pointed out (which means that I don't know if it's okay to include the source code here, and others won't know if it's okay to use it in their own projects). The other issue is that the name conflicts with a different [Minimal CSS](https://github.com/billyshall/minimalcss) which is already included and has an MIT license.

The Minimal CSS project we have now doesn't seem to be actively developed though (it was last updated 5 years ago), so I would be happy to switch it with this newer one if the license issue could be resolved. Perhaps it might be possible to open an issue at the minimal-stylesheet repo or reach out to @chr15m to request including a license for the stylesheet?

**Comment by chr15m** [comment]
:point_up: :+1:

**Comment by dohliam** [comment]
Awesome, thanks @chr15m! :+1:

@TheLastZombie if you'd still like to submit this PR, could you pull the latest changes to your branch and update the `scripts/frameworks.yml` file with the relevant info for Minimal CSS? There's no need to manually edit the readme or js script anymore, since they are now auto generated based on the data in the YAML file.

If it would be easier to submit this as a separate PR, that would be fine too. If I can help with anything just let me know!

**Comment by TheLastZombie** [comment]
Sounds good! Two questions though:

- Should I really remove Minimal CSS instead of just calling this one Minimal stylesheet CSS?
- Minimal stylesheet is actually split into two files, [one](https://github.com/chr15m/minimal-stylesheet/blob/master/minimal.css) for basic styles and [another](https://github.com/chr15m/minimal-stylesheet/blob/master/minimal-inputs.css) for inputs. Before, I simply merged the two files into one, but now? Maybe @chr15m could provide a single "merged" stylesheet.

**Comment by dohliam** [comment]
Hm, good points. I didn't notice that it was separated into two parts. Perhaps we could include the basic HTML version for now and if it's possible for @chr15m to release a combined version at some point we could switch to that instead? It would just be a quick adjustment to the stylesheet URL in the YAML file.

Also, good idea to name this `minimal-stylesheet` and keep the original `minimal` css in the repo! I think this will make a nice addition to the list.

**Comment by TheLastZombie** [comment]
This should work ~~hopefully~~.

**Pull request merged**
